version: '3'
services:
    mongo:
        image: mongo:6.0.1
        env_file:
            - './.env'
    redis:
        image: redis:7.0.4
        env_file:
            - './.env'
        command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD

    app:
        container_name: api_user_management
        build: .
        ports:
            - 8001:8001
        depends_on:
            - redis
            - mongo
