version: '3'
services:
    postgres:
        image: postgres:14
        env_file:
            - './.env'
    user_redis:
        image: redis:7.0.4
        env_file:
            - './.env'
    app:
        container_name: api_user_management
        build: .
        ports:
            - 8001:8001
        depends_on:
            - redis
            - mongo
